### ISSUE TITLE
Creating Singletons

### ISSUE THREAD

**Issue by bcowgill** [javascript/augment#9]
On your Getting Started wiki page you mention an upcoming article on:

Using augment to create modules and singleton instances.

I couldn't find this anywhere. Do you have an example?

**Comment by aaditmshah** [comment]
I added documentation for [modules and singletons](https://github.com/javascript/augment/wiki/Modules-and-Singletons). Thank you for pointing out this omission.

**Comment by bcowgill** [comment]
Thank you for the answer. I think you might have missed skalee's answer on the singleton thread you refer to. Despite only having 2 votes, I think it's the only Singleton taking full context of Javascript and Singleton in mind. http://stackoverflow.com/a/19458623 His point that delayed initialisation is probably down to the need for I/O and that means callbacks.  You alluded to this in your page as well by mentioning intensive operations like database connections.
